import { Token, TokenColumn } from "./types";

export const mockTokens: Record<TokenColumn, Token[]> = {
  newPairs: [
    {
      id: "np-1",
      name: "Somalian Somalian Simulator",
      symbol: "SOMALIAN",
      subtitle: "Somalian Simulator",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=SOMALIAN",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Ck3L...pump",
      price: 0.0001,
      priceChange: 8,
    },
    {
      id: "np-2",
      name: "Dafoe William Dafoe",
      symbol: "DAFOE",
      subtitle: "William Dafoe",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=DAFOE",
      volume: 814,
      marketCap: 3960,
      fees: 0.035,
      transactions: 20,
      timeAgo: "11s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 6 },
        { value: 3, timeframe: "10mo" },
        { value: 3 },
        { value: 0 },
        { value: 0 },
      ],
      address: "6bPZ...gKsX",
      price: 0.0002,
      priceChange: 6,
    },
    {
      id: "np-3",
      name: "Remilia The Cryptocurrency Wikipedia",
      symbol: "REMILIA",
      subtitle: "The Cryptocurrency Wikipedia",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=REMILIA",
      volume: 4000,
      marketCap: 7930,
      fees: 0.097,
      transactions: 57,
      timeAgo: "2d",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 27 },
        { value: 3, timeframe: "2d" },
        { value: 14 },
        { value: 0 },
        { value: 22 },
      ],
      address: "Remi...pedia",
      price: 0.0003,
      priceChange: 27,
    },
    {
      id: "np-4",
      name: "Tokyo Simulator",
      symbol: "TOKYO",
      subtitle: "Tokyo Simulator",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=TOKYO",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Tokyo...Simulator",
      price: 0.0001,
      priceChange: 8,
    },
    {
      id: "np-5",
      name: "William Dafoe",
      symbol: "DAFOE",
      subtitle: "William Dafoe",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=DAFOE",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Dafoe...William",
      price: 0.0001,
      priceChange: 8,
    },
    {
      id: "np-6",
      name: "William Dafoe",
      symbol: "DAFOE",
      subtitle: "William Dafoe",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=DAFOE",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Dafoe...William",
      price: 0.0001,
      priceChange: 8,
    },
    {
      id: "np-7",
      name: "William Dafoe",
      symbol: "DAFOE",
      subtitle: "William Dafoe",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=DAFOE",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Dafoe...William",
      price: 0.0001,
      priceChange: 8,
    },
    {
      id: "np-8",
      name: "Na Dafoe",
      symbol: "NICO",
      subtitle: "Nico Nico",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=NICO",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Nico...Nico",
      price: 0.0001,
      priceChange: 8,
    },
    {
      id: "np-9",
      name: "Allen Simulator",
      symbol: "ALLEN",
      subtitle: "Allen Simulator",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=ALLEN",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Allen...Simulator",
      price: 0.0001,
      priceChange: 8,
    },
    {
      id: "np-10",
      name: "Derek Simulator",
      symbol: "DEREK",
      subtitle: "Derek Simulator",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=DEREK",
      volume: 330,
      marketCap: 4180,
      fees: 0.023,
      transactions: 3,
      timeAgo: "1s",
      participants: 2,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 8 },
        { value: 3, timeframe: "5m" },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Derek...Simulator",
      price: 0.0001,
      priceChange: 8,
    },
  ],
  finalStretch: [
    {
      id: "fs-1",
      name: "EIG EIG Ponzi",
      symbol: "EIG",
      subtitle: "EIG Ponzi",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=EIG",
      volume: 11000,
      marketCap: 4800,
      fees: 0.041,
      transactions: 2,
      timeAgo: "2d",
      participants: 0,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 0 },
        { value: 0 },
        { value: 0 },
        { value: 0 },
        { value: 0 },
      ],
      address: "EIG...ponzi",
      price: 0.0004,
      priceChange: 0,
    },
    {
      id: "fs-2",
      name: "Subway Subway",
      symbol: "SUBWAY",
      subtitle: "Subway",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=SUBWAY",
      volume: 18000,
      marketCap: 674000,
      fees: 0.033,
      transactions: 32,
      timeAgo: "57s",
      participants: 0,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 19 },
        { value: 0 },
        { value: 19 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Sub...way",
      price: 0.0005,
      priceChange: 19,
    },
    {
      id: "fs-3",
      name: "Meta Fuel",
      symbol: "MFUEL",
      subtitle: "Meta Fuel Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=MFUEL",
      volume: 24000,
      marketCap: 98000,
      fees: 0.028,
      transactions: 41,
      timeAgo: "3m",
      participants: 3,
      votes: 2,
      progress: "1/2",
      percentages: [
        { value: 12 },
        { value: 10 },
        { value: 11 },
        { value: 0 },
        { value: 0 },
      ],
      address: "MFU...fuel",
      price: 0.00052,
      priceChange: 12,
    },
    {
      id: "fs-4",
      name: "Crypto Bull",
      symbol: "BULL",
      subtitle: "Bull Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=BULL",
      volume: 19500,
      marketCap: 85000,
      fees: 0.031,
      transactions: 38,
      timeAgo: "4m",
      participants: 4,
      votes: 3,
      progress: "1/2",
      percentages: [
        { value: 15 },
        { value: 12 },
        { value: 14 },
        { value: 0 },
        { value: 0 },
      ],
      address: "BUL...token",
      price: 0.00048,
      priceChange: 15,
    },
    {
      id: "fs-5",
      name: "Diamond Hands",
      symbol: "DIAMOND",
      subtitle: "Diamond Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=DIAMOND",
      volume: 22000,
      marketCap: 92000,
      fees: 0.029,
      transactions: 45,
      timeAgo: "2m",
      participants: 5,
      votes: 4,
      progress: "1/2",
      percentages: [
        { value: 18 },
        { value: 15 },
        { value: 16 },
        { value: 0 },
        { value: 0 },
      ],
      address: "DIA...hand",
      price: 0.00055,
      priceChange: 18,
    },
    {
      id: "fs-6",
      name: "Moon Shot",
      symbol: "MOON",
      subtitle: "Moon Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=MOON",
      volume: 26000,
      marketCap: 105000,
      fees: 0.032,
      transactions: 52,
      timeAgo: "5m",
      participants: 6,
      votes: 5,
      progress: "2/2",
      percentages: [
        { value: 22 },
        { value: 18 },
        { value: 20 },
        { value: 0 },
        { value: 0 },
      ],
      address: "MOO...shot",
      price: 0.00061,
      priceChange: 22,
    },
    {
      id: "fs-7",
      name: "Rocket Fuel",
      symbol: "ROCKET",
      subtitle: "Rocket Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=ROCKET",
      volume: 21000,
      marketCap: 88000,
      fees: 0.027,
      transactions: 43,
      timeAgo: "6m",
      participants: 3,
      votes: 2,
      progress: "1/2",
      percentages: [
        { value: 14 },
        { value: 11 },
        { value: 13 },
        { value: 0 },
        { value: 0 },
      ],
      address: "ROC...fuel",
      price: 0.00051,
      priceChange: 14,
    },
    {
      id: "fs-8",
      name: "Star Power",
      symbol: "STAR",
      subtitle: "Star Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=STAR",
      volume: 17500,
      marketCap: 79000,
      fees: 0.025,
      transactions: 36,
      timeAgo: "8m",
      participants: 2,
      votes: 1,
      progress: "1/2",
      percentages: [
        { value: 9 },
        { value: 7 },
        { value: 8 },
        { value: 0 },
        { value: 0 },
      ],
      address: "STA...power",
      price: 0.00046,
      priceChange: 9,
    },
  ],

  migrated: [
    {
      id: "mg-1",
      name: "homun I am the homunculus",
      symbol: "HOMUN",
      subtitle: "I am the homunculus",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=HOMUN",
      volume: 11000,
      marketCap: 43200,
      fees: 0.042,
      transactions: 4,
      timeAgo: "1h",
      participants: 0,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 75 },
        { value: 75 },
        { value: 75 },
        { value: 0 },
        { value: 0 },
      ],
      address: "Hom...culus",
      price: 0.0006,
      priceChange: 75,
    },
    {
      id: "mg-2",
      name: "KFC KFC",
      symbol: "KFC",
      subtitle: "KFC",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=KFC",
      volume: 12000,
      marketCap: 47700,
      fees: 0.021,
      transactions: 51,
      timeAgo: "5m",
      participants: 0,
      votes: 0,
      progress: "0/2",
      percentages: [
        { value: 74 },
        { value: 73 },
        { value: 73 },
        { value: 0 },
        { value: 0 },
      ],
      address: "KFC...colonel",
      price: 0.0007,
      priceChange: 74,
    },
    {
      id: "mg-3",
      name: "Chain Gorilla",
      symbol: "GORILLA",
      subtitle: "Chain Gorilla",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=GORILLA",
      volume: 45000,
      marketCap: 210000,
      fees: 0.019,
      transactions: 88,
      timeAgo: "12m",
      participants: 6,
      votes: 4,
      progress: "2/2",
      percentages: [
        { value: 32 },
        { value: 30 },
        { value: 31 },
        { value: 0 },
        { value: 0 },
      ],
      address: "GOR...illa",
      price: 0.0011,
      priceChange: 32,
    },
    {
      id: "mg-4",
      name: "Galaxy Token",
      symbol: "GALAXY",
      subtitle: "Galaxy Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=GALAXY",
      volume: 38000,
      marketCap: 185000,
      fees: 0.024,
      transactions: 76,
      timeAgo: "15m",
      participants: 5,
      votes: 3,
      progress: "2/2",
      percentages: [
        { value: 28 },
        { value: 26 },
        { value: 27 },
        { value: 0 },
        { value: 0 },
      ],
      address: "GAL...axy",
      price: 0.00095,
      priceChange: 28,
    },
    {
      id: "mg-5",
      name: "Phoenix Rise",
      symbol: "PHOENIX",
      subtitle: "Phoenix Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=PHOENIX",
      volume: 52000,
      marketCap: 245000,
      fees: 0.018,
      transactions: 102,
      timeAgo: "8m",
      participants: 8,
      votes: 6,
      progress: "2/2",
      percentages: [
        { value: 42 },
        { value: 38 },
        { value: 40 },
        { value: 0 },
        { value: 0 },
      ],
      address: "PHO...rise",
      price: 0.0013,
      priceChange: 42,
    },
    {
      id: "mg-6",
      name: "Thunder Bolt",
      symbol: "THUNDER",
      subtitle: "Thunder Token",
      icon: "https://api.dicebear.com/7.x/shapes/png?seed=THUNDER",
      volume: 29000,
      marketCap: 142000,
      fees: 0.022,
      transactions: 64,
      timeAgo: "20m",
      participants: 4,
      votes: 2,
      progress: "2/2",
      percentages: [
        { value: 25 },
        { value: 23 },
        { value: 24 },
        { value: 0 },
        { value: 0 },
      ],
      address: "THU...bolt",
      price: 0.00078,
      priceChange: 25,
    },
  ],
};
